### ISSUE TITLE
Text wrapping

### ISSUE THREAD

**Issue by ahmadjbara** [ObjectProcessMethodology/OPCloud-client#24]
The objective is to have shapes (rectangle, ellipse, rountangle) with height-to-width ratio of 9:16 (like modern computer screens) or smaller.
Example with state rountangles: This is acceptable:
![image](https://cloud.githubusercontent.com/assets/11922522/26755346/d79c081e-4893-11e7-83f0-e51fa66aeccb.png)
We don’t want something like this:
![image](https://cloud.githubusercontent.com/assets/11922522/26755350/e3f10d62-4893-11e7-8306-0ba5ac6e0185.png)
So I split the long line in 2:
![image](https://cloud.githubusercontent.com/assets/11922522/26755352/f893cff2-4893-11e7-8516-eee686d4e1a1.png)
I do fit to content and I get:
![image](https://cloud.githubusercontent.com/assets/11922522/26755354/03743894-4894-11e7-9678-0788e7e2c0cc.png)
Still too long so I split into 3 lines; after fit to content in OPCAT I get:
![image](https://cloud.githubusercontent.com/assets/11922522/26755359/0ce6047a-4894-11e7-949f-ddded2113e87.png)
This is acceptable.

Here is the **algorithm** (which I hope will work) for determining how to break long text:
Assume that the width occupied by n horizontal characters are equal to the height of the shape (n=4 is reasonable)
Let the number of chars in the text be N
If n/N > 9/16 and a new word started, open a new line and write the text there.
 
This way, the shape (rectangle, ellipse or rountangle) maintains aspect ratio of more or less 9:16 in real time, while the use is typing.
 
A user shall have the ability to override the automatic wrapping by resizing the shape, and the text will wrap according to the resized shape and remain this way until auto-wrapping is invoked again for this shape.
 
For now, font size changing will happen only for very long texts to fit the shape when the user manually reshapes the shape.

 The following is related to Oleg’s project:
If the user wants to homogenize a group of entities (states in an object or a set of marked processes or objects) the size of largest shape in the group determines the size of the remaining shapes. All the shapes are arranged horizontally or vertically or diagonally with equal distances between the shapes.

@dovdori 
@NataliLevi 
@B0BBB 
@shmool

**Comment by NataliLevi** [comment]
aspect ratio demand was changed to be 5/9 for objects\processes and 1\2 for states.
